sources = ['getAddress',
'getMacAddress',
'getCountry',
'getSSID',
'getCid',
'getLac',
'getLatitude',
'getLongitude',
'getLastKnownLocation',
'getDeviceId',
'getSubscriberId',
'getSimSerialNumber',
'getLine1Number',
'getInstalledApplications',
'getInstalledPackages',
'queryIntentActivities',
'queryIntentServices',
'queryBroadcastReceivers',
'queryContentProviders']

wenjianIO = ['java.io.FileOutputStream: void write(byte[])',
             'java.io.OutputStream: void write(byte[])',
             #'android.content.SharedPreferences$Editor:',
             #'android.content.SharedPreferences$Editor',
             #'putString(java.lang.String,java.lang.String)',
             'java.io.Writer: void write(char[])',
             '<java.io.OutputStream: void write(byte[])>',
             '<java.io.OutputStream: void write(byte[],int,int)>',
             '<java.io.OutputStream: void write(int)>',
             '<java.io.FileOutputStream: void write(byte[])>',
             '<java.io.FileOutputStream: void write(byte[],int,int)>',
             '<java.io.FileOutputStream: void write(int)>',
             '<java.io.Writer: void write(char[])>',
             '<java.io.Writer: void write(char[],int,int)>',
             '<java.io.Writer: void write(int)>',
             '<java.io.Writer: void write(java.lang.String)>',
             '<java.io.Writer: void write(java.lang.String,int,int)>',
             '<java.io.Writer: java.io.Writer append(java.lang.CharSequence)>',
             '<java.io.OutputStreamWriter: java.io.Writer append(java.lang.CharSequence)>']
             # '<android.content.SharedPreferences$Editor: android.content.SharedPreferences$Editor putBoolean(java.lang.String,boolean)>',
             # '<android.content.SharedPreferences$Editor: android.content.SharedPreferences$Editor putFloat(java.lang.String,float)>',
             # '<android.content.SharedPreferences$Editor: android.content.SharedPreferences$Editor putInt(java.lang.String,int)>',
             # '<android.content.SharedPreferences$Editor: android.content.SharedPreferences$Editor putLong(java.lang.String,long)>',
             # '<android.content.SharedPreferences$Editor: android.content.SharedPreferences$Editor putString(java.lang.String,java.lang.String)>']

handler= [
'<android.os.Handler: boolean sendMessage(android.os.Message)>']